"""
data_source.py
==============
A thin `DataSource` abstraction so the rest of the pipeline NEVER cares where
numbers come from. This is the concrete implementation of the
"build on simulation now, swap in real data later" strategy.

    DataSource
    ├── SyntheticSource   <- reads our generated CSVs  (this project)
    ├── BSISSource        <- placeholder for the Blood Safety Information System Web API
    └── DHIS2Source       <- placeholder for the national DHIS2 aggregate Web API

The two placeholders raise NotImplementedError today but carry the exact
field mapping needed to implement them (see ANALYSIS_PLAN.md "Data sources").
"""

from __future__ import annotations

import pandas as pd

from . import config


class DataSource:
    """Base interface. A source returns a tidy daily long table with columns:
        date, region, component, blood_group, units
    """

    kind = "base"

    def load_frame(self, measure: str) -> pd.DataFrame:
        """`measure` is one of {'collection', 'issuance'}."""
        raise NotImplementedError


class SyntheticSource(DataSource):
    """Reads the calibration data generated by synthetic_data.py."""

    kind = "synthetic"

    def load_frame(self, measure: str) -> pd.DataFrame:
        path = config.DATA_DIR / f"{measure}_long.csv"
        df = pd.read_csv(path, parse_dates=["date"])
        return df

    def national_daily(self) -> pd.DataFrame:
        """Convenience: national total collection & issuance per day."""
        df = pd.read_csv(config.DATA_DIR / "national_daily.csv",
                         parse_dates=["date"])
        return df


class BSISSource(DataSource):
    """TODO(real data): pull from the Blood Safety Information System Web API.

    Expected mapping (proposal Table section 3.2):
        collection date  -> BSIS donor / collection logs
        collection units -> BSIS test results    (de-identified aggregates)
        component        -> BSIS component preparation logs
        blood_group      -> BSIS immunohematology
    De-identify and aggregate at source before analysis. Requires the
    EBTBS/HABTech System-of-Record agreement (proposal SOP 1).
    """

    kind = "bsis"

    def load_frame(self, measure: str) -> pd.DataFrame:
        raise NotImplementedError(
            "BSISSource requires live BSIS Web API credentials and an "
            "active EBTBS/HABTech agreement. Implement load_frame() with the "
            "field mapping documented in ANALYSIS_PLAN.md."
        )


class DHIS2Source(DataSource):
    """TODO(real data): pull from the national DHIS2 aggregate instance.

    Expected mapping:
        transfusion requests -> DHIS2 data elements
        bed occupancy        -> HMIS/DHIS2 indicator
        emergency obstetric admissions -> DHIS2 indicators
    Use the DHIS2 REST analytics API (`/api/analytics`). Prototype against a
    public demo instance first.
    """

    kind = "dhis2"

    def load_frame(self, measure: str) -> pd.DataFrame:
        raise NotImplementedError(
            "DHIS2Source requires a DHIS2 instance URL + credentials."
        )


def get_source(name: str = "synthetic") -> DataSource:
    """Factory: return the configured DataSource implementation."""
    sources = {
        "synthetic": SyntheticSource,
        "bsis": BSISSource,
        "dhis2": DHIS2Source,
    }
    return sources[name]()
